version: '3.7'

services:
  browserver:
    image: browserver
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - ./data:/app/data
    restart: always
    ports:
      - 5434:3000
    logging:
      options:
        max-size: 5m
